load("@bazel_tools//tools/build_defs/repo:http.bzl","http_file")

http_file(
    name = "my-custom-tool.exe",
    url = "https://upload.wikimedia.org/wikipedia/commons/c/c5/Big_buck_bunny_poster_big.jpg",
)