new_local_repository(
    name = "external-raw-data",
    build_file_content = """
genrule(
    name = "convert-to-csv",
    visibility = ["//visibility:public"],
    srcs = ["//:raw_data.txt"],
    outs = ["out.csv"],
    cmd = "cat $(location //:raw_data.txt) > $(location out.csv)"
)
    """,
    path = "C:\\Work\\bazel-tips-and-tricks\\external-raw-data",
)
